projectmanagement/config/routes.rb
Rails.application.routes.draw do
  resources :projects
  root :to => 'projects#index'

end

projectmanagement/app/models/person.rb
class Person < ActiveRecord::Base
end

projectmanagement/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  has_many :people
  belongs_to :owner, :class_name => 'Person'

  has_many :project_tags
  has_many :tags, :through => :project_tags, :class_name => 'Tag'

  accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :people, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :owner, :reject_if => :all_blank
  accepts_nested_attributes_for :tags
  accepts_nested_attributes_for :project_tags, :allow_destroy => true
end

projectmanagement/app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :project

  accepts_nested_attributes_for :tag, :reject_if => :all_blank
end

projectmanagement/app/models/sub_task.rb
class SubTask < ActiveRecord::Base
  belongs_to :task
end

projectmanagement/app/models/tag.rb
class Tag < ActiveRecord::Base
end

projectmanagement/app/models/task.rb
class Task < ActiveRecord::Base
  has_many :sub_tasks
  accepts_nested_attributes_for :sub_tasks, :reject_if => :all_blank, :allow_destroy => true
end

projectmanagement/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

projectmanagement/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end

  private

  def project_params
    params.require(:project).permit(
        :name, :description, :owner_id,
        tasks_attributes: [:id, :_destroy, :name, :description, sub_tasks_attributes: [:id, :_destroy, :name, :description] ],
        people_attributes: [:id, :name, :role, :description, :_destroy],
        owner_attributes: [:id, :name, :role, :description, :_destroy],
        project_tags_attributes: [:id, :_destroy, :tag_id, tag_attributes: [:id, :_destroy, :name]]
    )
  end
end

projectmanagement/app/helpers/application_helper.rb
module ApplicationHelper
end

projectmanagement/app/helpers/projects_helper.rb
module ProjectsHelper
end

projectmanagement/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectmanagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

projectmanagement/app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name, :hint => 'The title of your project' %>
  <ul class='nav nav-tabs' role='tablist'>
    <li class='active'>
      <%= link_to 'Tasks (:has_many --nested)', '#tasks', data: {toggle:'tab'}%>
    </li>
    <li>
      <%= link_to 'People (:has_many)', '#people', data: {toggle:'tab'}%>
    </li>
    <li>
      <%= link_to 'Owner (:belongs_to)', '#owner', data: {toggle:'tab'}%>
    </li>
    <li>
      <%= link_to 'Tags (:has_many :through)', '#tags', data: {toggle:'tab'}%>
    </li>
  </ul>

  <!-- more here -->

<% end %>

projectmanagement/app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th><th>Actions</th>
    </tr>
  </thead>
  <tbody>
  	<% @projects.each do |project| %>
      <tr>
      	<td><%= project.name %></td>
      	<td>
      	  <%= link_to 'Show', project_path, :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Edit', edit_project_path, :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Destroy', project_path, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger btn-xs' %>
      	</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Project', new_project_path %>

projectmanagement/app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>